### ISSUE TITLE
Examples of glossary entries

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#107]
To give the reader an impression of my big table (alluded to in #96), I thought about including some entries in a table to show how this information is captured. Is this too low-level? For better display, I was thinking that some information could be left out (of course with a note explaining this), such as the following; thoughts?
 - the notes column
 - the sources for each piece of information
 - "extra" entries in the category and parent(s) columns

![image](https://github.com/user-attachments/assets/e0609f61-9e35-42ec-bb93-15579fe9847e)

**Comment by smiths** [comment]
I like the idea of showing an excerpt from your table in Chapter 1.  You will want to keep the detail in the columns, to show the richness of the data your are building.  You don't have to explain all the details, just enough so that the reader can understand the point of the table.  I think if you remove the Notes column at the end the spacing shouldn't be too busy/cluttered.
