### ISSUE TITLE
Dr. Carette's Review of Introduction (and Scope?)

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#111]
**Links**: [thesis](https://github.com/samm82/TestGen-Thesis/blob/main/thesis.pdf) and [paper](https://github.com/samm82/TestGen-Thesis/blob/main/paper.pdf)
**Introduction**: Chapter 1 of thesis and Section I of paper
**Scope**: Chapter 2 of thesis and Section II of paper

Following my response to #96, I'm ready for your review of these sections! Looking into various online resources for writing intros (to theses _and_ papers), I can really only find generic advice that I've already been following: start broad, focus in on your target area, make the reader care, justify the problem, introduce your research questions, etc. I'm not sure how long an introduction should be, especially given that it makes the most sense to write it _last_, since then you will have a more in-depth picture of the overall "story" of the thesis.

Regardless, I think the introduction is ready for review. Since it is a smaller and more trivial section, the Scope section is also ready for review (and was reviewed alongside the intro by @smiths). I'll leave it up to your judgement to review the Scope as well or wait until I've had a chance to respond to your Intro feedback (which also might suggest improvements to the Scope section).

**Comment by JacquesCarette** [comment]
The introduction still needs work. It's too haphazard. You should have more structure. For example this [guide to writing an introduction](https://www.monash.edu/student-academic-success/excel-at-writing/how-to-write/thesis-chapter/introduction-and-conclusion-thesis-chapters) is quite good.

You also start with 2 unjustified sentences, which is not good. I'll upload a marked-up copy of the start of the introduction - but I gave up partway through (even though it is quite short) because it was clear that the very structure of the introduction needed to change, and so there is no point to me reviewing things in minute detail in the current form.

[thesis-Sam.pdf](https://github.com/user-attachments/files/18187439/thesis-Sam.pdf)

**Comment by samm82** [comment]
Closed with #126.
