### ISSUE TITLE
Defining "synonym"

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#123]
In [this comment](https://github.com/samm82/TestGen-Thesis/issues/91#issuecomment-2356172760), @smiths says "Do you define earlier in the thesis what you mean by synonym and how they are detected? Do you give examples. Examples will help."

# Definition of "Synonym"
I currently have a bit of explanation of what is meant by "synonym"; there isn't really any "special" meaning to the term in my thesis; just two terms that mean the same (e.g., refer to the same test approach). This is currently in the discrepancies section to explain that they aren't intrinsically discrepancies, but I could move this to the terminology section to explicitly explain what I mean by "synonym". Is there anything that jumps out that I should add to this description (i.e., anything that's ambiguous)? (This also includes an example of some synonyms; would these be sufficient?)

![syn rel discreps](https://github.com/user-attachments/assets/ef9f698f-7670-4043-b9ac-fa7a962b3acc)

# Detecting Synonyms
Synonym relations are tracked in my glossaries as their own column, along with the relevant source(s). I also include an example table excerpt along with the resulting graph to demonstrate how this information is tracked and analyzed. Would this be sufficient, or is there still ambiguity? Does this make sense in the Tools section? (I personally think so, since it focuses on how graphs are generated, although the example tables could potentially be moved to the Methodology section.)

![syn table](https://github.com/user-attachments/assets/af131367-36fc-4f89-bee8-eeaab9cdf18c)
![syn graph](https://github.com/user-attachments/assets/4c84f61a-d102-402c-94eb-6d68bfe71a0c)

**Comment by smiths** [comment]
The explanation and examples sound great.  You don't need more examples.  However, you should clarify where the classification as synonyms comes from.  You don't have to say it with the text you gave above, but somewhere in your thesis you should say it.  (You probably already do.)  Specifically, I'm thinking that you distinguish synonyms that are identified as synonyms explicitly by the source, and those that are implicit.  Are there synonyms that you identified on your own, because the definitions were similar in your opinion?  If that is ever the case, you will want to be sure to point that out.  

What got me thinking about this is domain testing as a synonym for specification testing.  At first glance, these don't seem like the same thing to me.  I think all of your justifications are in the citations that you provide, but I don't want to assume this is the case without checking with you.  :smile:

**Comment by smiths** [comment]
Great!  Yes, I meant that you "should lay out the criteria [you used] for identifying synonyms".  The text showing that domain testing is explicitly stated to be a synonym for specification-based testing is what I was hoping for.  To be honest, it is not obvious to me at all that they are the same thing, partly because I don't think I know what domain testing is.  :smile:  Glad I will have your thesis so I can look up all these definitions!  :smile:

**Comment by samm82** [comment]
So far in my table, we have domain analysis ("a combination of equivalence partitioning and boundary value analysis" (IEEE, 2021, p. 11; OG Beizer 1995)) that may or may not be a test approach at all, and domain-based, -independent, and -specific testing, all given by Firesmith (2015) with no definitions 😅 so "domain testing" might not even be that useful of a term at all other than a possible synonym to specification-based testing 💀

**Comment by smiths** [comment]
You have a wealth of information in your table @samm82.  I'm impressed you could investigate my implied question so quickly.  The fact that people introduce terms, like domain-based testing, without a defining them, is certainly something we can criticize about the "state of the practice".  :smile:
