### ISSUE TITLE
Figure out ellipses

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#13]
Currently, `\dots` is used. Should `\ldots` be used? How should the case of four dots be handled (an example is currently in the Generating Test Cases section)?

**Comment by JacquesCarette** [comment]
It really depends on the actual use! Normally `\ldots` is the most common case.

**Comment by smiths** [comment]
A [stack exchange post](https://tex.stackexchange.com/questions/77737/what-is-the-difference-between-dots-and-ldots) suggest that `\dots` means not having to remember details on how the dots will appear because it switches between `\ldots` and `\cdots` as appropriate.  I don't know the context of this conversation though.  :smile:

**Comment by samm82** [comment]
This was mainly based off of [this LaTeX doc](https://www.read.seas.harvard.edu/~kohler/latex.html), really touting the use of `\dots`, which performs the same as `\ldots` in text mode. Since there is no macro for an ellipses with four dots, I just followed the semantics of what I was trying to communicate in the following line:
https://github.com/samm82/TestGen-Thesis/blob/23de3894c5581addf7846ab71017e9246640ab72/chapters/03_notes.tex#L1412
Since the quote ends with a period, then omits some sentences, then continues, the ellipses goes after the period.

I now use ellipses as follows:
- Normal use case: `text \dots\ text`
- Omission after period `text. \dots\ text`
- Omission before period `text\dots. text`
- "Trailing off" at the end of a (non-quoted) sentence: `text\dots text`
