### ISSUE TITLE
Ambiguity about meaning of "path" in testing literature

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#2]
From [my thesis notes](https://github.com/samm82/TestGen-Thesis/blob/main/notes.pdf) (currently p. 28):

> Path coverage: “[a]ttempting to cover all the paths in the software” [6, p. 119]; I always thought the “path” in “path coverage” was a path from program start to program end, but van Vliet seems to use the more general definition (which is, albeit, sometimes valid, like in “du-path”) of being any subset of a program’s execution (see [7, p. 420])

What are your definitions of a "path" in a software? It is required to begin at the start of the code? Should we make the decision of a definition to use consistently, or should I review the literature further to see if the clarifies things? (See what is currently Q4.)

Regardless of our path forward (pun unintended), I think this will be interesting to include in my thesis somewhere.

**Comment by smiths** [comment]
@samm82 I've always thought that path coverage can be assessed for any unit of code.  It doesn't have to be the entire program.  A function can be tested for path coverage; it doesn't have to be the entire program.  Since path coverage is so difficult to achieve, being able to focus on subsets of the code is valuable.  The critical portion of the code can be tested for path coverage, rather than trying for the (usually) unrealistic goal of path coverage for everything.

**Comment by samm82** [comment]
That's a good clarification: "path" can be "path through a module" just as much as "path through the system". I'll keep this issue open until I actually incorporate this information into my thesis in a meaningful way

**Comment by samm82** [comment]
Turns out the best way to deal with discrepancies was just to document them! (You can tell this was EARLY on in my research when we didn't realize how many discrepancies there would be. 💀)
