### ISSUE TITLE
Usefulness of organization- and role-based testing in the test approaches glossary

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#59]
How useful would the kinds of [organization-based testing](https://apps.dtic.mil/sti/pdfs/AD1147163.pdf#page=37) and [role-based testing](https://apps.dtic.mil/sti/pdfs/AD1147163.pdf#page=39) be? I know they should probably be included for completeness, but also don't want to get into the weeds of understanding the org chart of the software world as a whole. The ones that seem useful from role-based testing are already captured (developer testing, independent tester testing (to an extent), buddy testing, pair testing, user testing (to an extent), and beta (plus its variants)). Am I OK to just make a note of this and leave it out of my table, or should I be making more rows? 😅

![image](https://github.com/samm82/TestGen-Thesis/assets/35857611/9dfdceb5-d616-423f-82b9-7fa3dc71a9dd)
![image](https://github.com/samm82/TestGen-Thesis/assets/35857611/f2dea3aa-33be-4659-bc9b-2cc114b97315)

**Comment by smiths** [comment]
@samm82 my instinct is to include all the types of testing you have listed above.  They are legitimate types of testing classified by "who" and "role".   You very likely will have this categorization of testing as well.  It is getting a little silly, but I think that will be part of the point of your thesis.  For testing we need to know who is going to do the testing, but do we really need to name a type of testing after each possible who?  Maybe rather than name each kind of testing, we'll recommend a series of fields that need to be filled in when one is planning their testing activities, including who will do the testing?

I don't think it will be too much work to include these extra tests in your table.  I doubt you will find any specialized literature on most of these "new" test types.  Your definitions will likely be something you need to write with the only clue being the name of the test type.  I doubt these types of tests will make the cut when we start restricting the scope for deeper analysis.

Another reason to include these is that we don't have a criterion to use to exclude them.  We could add a criterion, but I would worry that it would sound arbitrary and only motivated by keeping our list shorter.  :smile:

**Comment by samm82** [comment]
Added these test approaches to (potentially) investigate later; we are now past 400!
