### ISSUE TITLE
Submit Abstract to ICSE 2025

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#60]
**DUE: Fri 26 Jul 2024**

This is for the second cycle of the [research track](https://conf.researchr.org/track/icse-2025/icse-2025-research-track).

Just making a note for me so I don't forget and can pace myself! 😅

**Comment by samm82** [comment]
When writing this paper (and its abstract), the goal should really be analyzing our results to propose a solution to the problem of "inconsistent testing terminology/organization", not just highlighting it. To do this, I should start on the analysis phase _now_, and continue to fill in my table as a (lower priority) parallel task. We should aim to be bold and "provocative" in this paper to really sell its merit, meaning that coming up with a good title should be a priority.

**Comment by JacquesCarette** [comment]
Agreed!

**Comment by samm82** [comment]
@smiths Some minor questions I had about this submission; more in-depth questions will be asked as separate issues:

1. When it says that the abstract is due, does that mean _literally just_ the abstract, and that the submission date (a week after; Aug 2) is when I'd actually need the full paper ready for?
2. Throughout my document, I've been keeping track of relevant issues for traceability; obviously I should remove these for the anonymous submission, but is it worth it to keep them for my thesis, at least while I'm still writing it?

**Comment by JacquesCarette** [comment]
1. yes
2. I think so.

**Comment by samm82** [comment]
@smiths @JacquesCarette I know this is pretty last-minute, but here is what I have for an abstract so far! The deadline for submission is 8am tomorrow morning, so I'll hopefully have some time to implement any feedback you give. If not, I'll submit as-is:

>Testing software is complicated, expensive, and often overlooked. Therefore, automating the software testing process is an area of interest, and understanding the underlying domain is an important prerequisite. Since existing software testing taxonomies are inadequate, the literature was investigated to attempt to build one that is systematic, rigorous, and "complete". Through this process, over five hundred test approaches were uncovered, as well as a (relatively) consistent method for classifying them and some methods for describing "implied" test approaches. In addition, a tool was built to automatically generate graphs based on the relations between them and track their ambiguities, in addition to those captured manually through the research process. As of now, ten terms were given as synonyms to two (or more) disjoint test approaches and fourteen pairs of test approaches may be synonyms and/or have a child-parent relationship. There is also notable confusion around the terms "functional testing", "recovery testing", "scalability testing", and "performance testing", as well as over fifty more "minor" discrepancies. Overall, there is a need for testing terminology to be standardized to allow for consistency when discussing, analyzing, and/or implementing software testing.

**Comment by smiths** [comment]
Thank you for sending @samm82.  I only have a short window to review, but I'll do my best to give some quick feedback.  I remain excited about this topic, but the abstract you've written probably won't generate excitement from the reader.  :smile:  Try revising following something like the following outline:

- testing is a critical part of every software development project
- new research, books, software tools, processes etc related to testing are created every year (this might be better in the introduction than in the abstract)
- unfortunately, this work is built on an unstable foundation
- unambiguous communication on testing is impossible because the definitions of testing approaches and the relationships between them are not standardized; there is no standard, complete and consistent taxonomy for testing.
- disagreements and inconsistencies exist between standards, within standards, and between standards and the current literature on testing taxonomies
- we investigated this through a systematic methodology where we 1) identified the key resources (such as IEEE, SWEBOK, [add others here]), 2) systematically went through each resource to capture the definitions and their relationships (both explicit and implied), 3) built graphs summarizing this data, and 4) analyzed the graphs.
- Our results show ten terms were given as synonyms to two (or more) disjoint test approaches and fourteen pairs of test approaches may be synonyms and/or have a child-parent relationship. There is also notable confusion around the terms "functional testing", "recovery testing", "scalability testing", and "performance testing", as well as over fifty more "minor" discrepancies. Overall, there is a need for testing terminology to be standardized to allow for consistency when discussing, analyzing, and/or implementing software testing.
- We provide some initial advice on building a standard taxonomy for testing.

You also need a title for the paper.

I won't be back to my computer until late tonight.  If you can provide a new draft @samm82, I'll go through it.  If you could also brainstorm some titles that would be great.

**Comment by samm82** [comment]
My current working title is "Putting Software Testing Terminology to the Test"; the subtitle of my poster was "Seeking More Standardized Standards", which could be adjusted into "Seeking More Standardized Standards for Software Testing".

Is the omission of "test case generation" from the abstract intentional? I think it would make sense to include in the Background section, but maybe not in the abstract.

> disagreements and inconsistencies exist between standards, within standards, and between standards and the current literature on testing taxonomies

I'm not sure how worth it it would be to put this in the abstract; would it be more worth it to include this alongside the analysis/discussion of these different subset? If we wanted to highlight the extent of these discrepancies, maybe something like "disagreements; sometimes even within the same document!"

**Comment by samm82** [comment]
Version 2:

> Testing is a critical part of every software development project that is often complicated, expensive, or overlooked. This is in part due to the unstable knowledge base; there is no standard, consistent, and "complete" taxonomy for software testing, which inhibits unambiguous communication. Discrepancies and ambiguities are widespread throughout the literature, and sometimes exist between different parts of the same document! We systematically investigate the current state of software terminology by 1) identifying established standards (including IEEE, ISO/IEC, and SWEBOK) and other prominent testing resources, 2) capturing relevant testing terms from these sources, along with their definitions and relationships (both explicit and implied), and 3) building graphs to visualize and analyze these data. Throughout this process, over five hundred test approaches were uncovered, as well as some methods for describing "implied" test approaches. In addition, a tool was built to generate graphs of the relations between test approaches and track their ambiguities, in addition to those captured manually through the research process. Our results show ten terms are given as synonyms to two (or more) disjoint test approaches and fourteen pairs of test approaches may be synonyms and/or have a child-parent relationship. There is also confusion surrounding functional, recovery, scalability, and performance testing, along with over fifty more "minor" discrepancies. Overall, there is a need for testing terminology to be standardized to make the discussion, analysis, and implementation of various test approaches more coherent, and we provide some preliminary advice on how to accomplish this.

**Comment by smiths** [comment]
I like this version @samm82.  I think we'll likely want to make some changes before the final version, especially after the paper is written, but this is a good starting point.  I also like your proposed title.  Let's go with that.

Yes, omitting test generation from the abstract is intentional.  That is part of what motivated us, but it isn't the focus of your paper.  This seems like something you could mention under future work, or possibly not at all.  The paper is about the problems with testing terminology, with some initial thoughts on how to fix it.  It isn't about test case generation.

**Comment by JacquesCarette** [comment]
Sorry, time zone (and travel schedule) meant that I couldn't really review this along the needed timelines.

Luckily the abstract is now good, what I'd want to do is various tweaks that don't really matter at this stage of submission.

**Comment by samm82** [comment]
In that case, abstract submitted and issue closed, with one for submitting the first draft of the paper (due a week from now) coming soon!

**Comment by smiths** [comment]
Thank you for driving this forward @samm82.  Hopefully the paper comes together nicely.  I'm optimistic.  We can revise the abstract once the paper has been written.
