### ISSUE TITLE
Document graph analysis tool

### ISSUE THREAD

**Issue by samm82** [samm82/TestGen-Thesis#82]
We've previously mentioned that I should include some content describing how I developed the graph analysis tool and how it works. Where should this go @smiths, as a subsection of Methodology?

Dr. Smith mentioned in his review of my paper (see #74) that "a sample graph, showing how I identify errors, like the disjoint synonyms, would be great.… Give some examples of the graph characteristics you are looking for." I'm thinking that this should be a complete dummy graph (e.g., with nodes labelled "A", etc.) as to not confuse the analysis of the graph with the specific relations between testing terms.

**Comment by smiths** [comment]
@samm82 there are three aspects of the graph analysis tool that you should document:

- the general use of the tool (user instructions)
- the specific rules the tool uses to find questionable relations in the graph
- the implementation of the tool

The general use of the tool is something you want to document so that others can use your tool.  We should make your data and code available to other researchers.  You will want to write a brief user guide that helps people get started.  This would likely be an Appendix to your thesis and it would exist in your open source repo.

The specific rules are what you are describing in the second paragraph above.  Yes, they should go in the methodology section, and yes you should document them in a generic way (with approaches labelled A, B, etc.).

The implementation will likely be of interest to some readers, especially since this is a SE thesis.  My guess is that this would fit in an Appendix.  If you did something particularly noteworthy and novel, then it might be better as a chapter of your thesis.
